Basic imports and environment checks:
- PyTorch version verification is essential for reproducibility
- CUDA availability check - we'll need GPU access for future assignments
- If CUDA isn't available, try nvidia-smi in terminal to check GPU status

In [2]:
import torch

print(f"PyTorch version: {torch.__version__}")
print(f"CUDA available: {torch.cuda.is_available()}")

PyTorch version: 2.3.1+cu118
CUDA available: True


Converting Python list to tensor - torch.as_tensor() is preferred over torch.tensor()
as it can share memory with original data

In [3]:
x = [1, 2, 3, 4, 5]
x = torch.as_tensor(x)
print(x)

tensor([1, 2, 3, 4, 5])



A module that was compiled using NumPy 1.x cannot be run in
NumPy 2.3.5 as it may crash. To support both 1.x and 2.x
versions of NumPy, modules must be compiled with NumPy 2.0.
Some module may need to rebuild instead e.g. with 'pybind11>=2.12'.

If you are a user of the module, the easiest solution will be to
downgrade to 'numpy<2' or try to upgrade the affected module.
We expect that some modules will need time to support NumPy 2.

Traceback (most recent call last):  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "c:\Users\andyy\miniconda3\envs\deeplearning\Lib\site-packages\ipykernel_launcher.py", line 18, in <module>
    app.launch_new_instance()
  File "c:\Users\andyy\miniconda3\envs\deeplearning\Lib\site-packages\traitlets\config\application.py", line 1075, in launch_instance
    app.start()
  File "c:\Users\andyy\miniconda3\envs\deeplearning\Lib\site-packages\ipykernel\kernelapp.py", line 739, in start
    self.io_lo

Creating zero-filled tensor - useful for initializing buffers or placeholder tensors

In [4]:
x = torch.zeros(3, 4)
print(x)

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])


Creating tensor filled with ones - commonly used for masks or initialization

In [5]:
x = torch.ones(3, 4)
print(x)

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])


Creating tensor with custom fill value - useful when you need specific constant values

In [6]:
x = torch.full((3, 4), fill_value=2)
print(x)

tensor([[2, 2, 2, 2],
        [2, 2, 2, 2],
        [2, 2, 2, 2]])


Random tensor from normal distribution - key for weight initialization

In [7]:
x = torch.randn(3, 4)
print(x)

tensor([[-0.8272, -0.3084,  1.3424, -0.5170],
        [-2.2122,  1.4398, -0.1031,  0.8546],
        [-0.9136,  0.0140,  1.4582,  0.5651]])


`zeros_like` creates tensor with same shape/dtype as input but filled with zeros

In [8]:
x = torch.randn(3, 4)
y = torch.zeros_like(x)
print(y)

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])


`ones_like` - similar to before but fills with ones

In [9]:
x = torch.randn(3, 4)
y = torch.ones_like(x)
print(y)

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])


`full_like` - creates tensor matching input shape but with custom fill value

In [10]:
x = torch.randn(3, 4)
y = torch.full_like(x, 5)
print(y)

tensor([[5., 5., 5., 5.],
        [5., 5., 5., 5.],
        [5., 5., 5., 5.]])


`new_tensor` creates tensor with inherited properties (device/dtype) from source

In [11]:
x = torch.zeros(3, 4, dtype=torch.bool)
y = x.new_tensor([1, 2, 3, 4])
print(y)

tensor([True, True, True, True])


Broadcasting example with 2D tensors - shows automatic size matching

In [12]:
x = torch.ones(5, 1)
y = torch.ones(1, 5)
z = x + y
print(z, z.shape)

tensor([[2., 2., 2., 2., 2.],
        [2., 2., 2., 2., 2.],
        [2., 2., 2., 2., 2.],
        [2., 2., 2., 2., 2.],
        [2., 2., 2., 2., 2.]]) torch.Size([5, 5])


Complex broadcasting with 5D tensors - demonstrates multi-dimension expansion

In [13]:
x = torch.ones(1, 1, 1, 1, 1)
y = torch.ones(2, 1, 3, 1, 2)
z = x + y
print(z, z.shape)

tensor([[[[[2., 2.]],

          [[2., 2.]],

          [[2., 2.]]]],



        [[[[2., 2.]],

          [[2., 2.]],

          [[2., 2.]]]]]) torch.Size([2, 1, 3, 1, 2])


Mean reduction - shows global and dimensional mean calculations

In [14]:
x = torch.ones(3, 4, 5)
print(x.mean())
print(x.mean(-1))

tensor(1.)
tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])


Sum reduction - demonstrates summing across specified dimensions

In [15]:
x = torch.ones(3, 4, 5)
print(x.sum(dim=0))
print(x.sum(dim=(1, 2)))

tensor([[3., 3., 3., 3., 3.],
        [3., 3., 3., 3., 3.],
        [3., 3., 3., 3., 3.],
        [3., 3., 3., 3., 3.]])
tensor([20., 20., 20.])


`keepdim`` usage - shows difference in output shapes

In [16]:
x = torch.ones(3, 4, 5)
y = x.sum(dim=(1, 2))
z = x.sum(dim=(1, 2), keepdim=True)
print(y, y.shape)
print(z, z.shape)

tensor([20., 20., 20.]) torch.Size([3])
tensor([[[20.]],

        [[20.]],

        [[20.]]]) torch.Size([3, 1, 1])


Type conversion example - converting float tensor to long (int64)

In [17]:
x = torch.randn(5, 5)
print(x.to(torch.long))

tensor([[ 0,  0,  0, -1,  0],
        [ 0,  0,  0,  0,  0],
        [ 0,  0,  0,  0, -1],
        [ 0, -1,  0,  0,  0],
        [ 0,  0,  0,  0,  1]])


Reshaping with view - maintains underlying data pointer

In [18]:
x = torch.randn(2, 3, 2)
y = x.view(6, 2)
z = x.view(-1, 2)
print(y, y.shape)
print(z, z.shape)

tensor([[ 0.3934,  0.3443],
        [-0.5700, -0.2807],
        [ 0.3892,  0.8671],
        [-0.0926,  0.9348],
        [-0.0926,  0.6825],
        [ 0.6753,  2.3665]]) torch.Size([6, 2])
tensor([[ 0.3934,  0.3443],
        [-0.5700, -0.2807],
        [ 0.3892,  0.8671],
        [-0.0926,  0.9348],
        [-0.0926,  0.6825],
        [ 0.6753,  2.3665]]) torch.Size([6, 2])


Permute operation - reorders dimensions of tensor

In [19]:
x = torch.randn(2, 3, 2)
y = x.permute(1, 2, 0)
print(y, y.shape)

tensor([[[ 0.2465, -0.1852],
         [ 0.8052,  0.1805]],

        [[ 0.4975, -0.2125],
         [ 1.0052, -0.3668]],

        [[-1.7519,  1.5638],
         [-0.1023,  0.3570]]]) torch.Size([3, 2, 2])


Concatenation along specified dimension

In [20]:
x = torch.ones(2, 3)
y = torch.ones(2, 3)
z = torch.cat([x, y], dim=0)
print(z, z.shape)

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]]) torch.Size([4, 3])


Stack operation - adds new dimension for combining tensors

In [21]:
x = torch.ones(2, 3)
y = torch.ones(2, 3)
z = torch.stack([x, y], dim=1)
print(z, z.shape)

tensor([[[1., 1., 1.],
         [1., 1., 1.]],

        [[1., 1., 1.],
         [1., 1., 1.]]]) torch.Size([2, 2, 3])


Performance comparison: Python list operations vs PyTorch operations

In [22]:
import time


def add_two_lists(x, y):
    z = []
    for i, j in zip(x, y):
        z.append(i + j)
    return z


x = torch.ones(5000)
y = torch.ones(5000)
t1 = time.time()
z = add_two_lists(x, y)
print(f"{time.time() - t1:.4f} sec.")

0.0275 sec.


PyTorch vectorized operation - significantly faster

In [23]:
def add_two_lists(x, y):
    return x + y


x = torch.ones(5000)
y = torch.ones(5000)
t1 = time.time()
z = add_two_lists(x, y)
print(f"{time.time() - t1:.4f} sec.")

0.0015 sec.


Type conversion examples - showing different conversion methods

In [24]:
x = torch.randn(3, 3)
y = torch.zeros(5, 2, dtype=torch.long)
print(x.to(torch.float32))
print(x.to(torch.bool))
print(x.to(y))

tensor([[-0.2524,  0.4250, -1.2308],
        [ 0.3156, -0.0648,  0.5266],
        [-1.7453,  0.9105, -0.3205]])
tensor([[True, True, True],
        [True, True, True],
        [True, True, True]])
tensor([[ 0,  0, -1],
        [ 0,  0,  0],
        [-1,  0,  0]])


`arange` examples - different ways to create sequences

In [25]:
x = torch.arange(8)
print(x)
y = torch.arange(2, 8)
print(y)
z = torch.arange(3, 10, step=2)
print(z)

tensor([0, 1, 2, 3, 4, 5, 6, 7])
tensor([2, 3, 4, 5, 6, 7])
tensor([3, 5, 7, 9])


In [ ]:
x = torch.tensor([[1.0, 2.0], [3.0, 4.0]], dtype=torch.float32)

print(torch.mean(x, dim=0))
print(torch.std(x, dim=0))

tensor([1.5000, 3.5000])
tensor([1.4142, 1.4142])
